# Use an official Python runtime as a parent image
FROM python:3.11.4-slim-buster

RUN apt-get update && apt-get install -y build-essential

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY tuning.py /app
COPY requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run the script when the container launches
CMD ["python", "tuning.py"]